# Generated by Django 6.0.3 on 2026-04-04 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('dynamic_rules', models.JSONField(blank=True, default=dict)),
                ('is_dynamic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.devicegroup')),
            ],
            options={
                'db_table': 'device_group',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('os_family', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows'), ('macos', 'macOS')], max_length=20)),
                ('os_version', models.CharField(max_length=100)),
                ('os_arch', models.CharField(default='x86_64', max_length=20)),
                ('agent_version', models.CharField(blank=True, max_length=20)),
                ('environment', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('development', 'Development'), ('test', 'Test')], default='production', max_length=20)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('decommissioned', 'Decommissioned')], default='offline', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('agent_api_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_checkin_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='devices', to='inventory.devicegroup')),
            ],
            options={
                'db_table': 'device',
                'indexes': [models.Index(fields=['status', 'os_family'], name='device_status_f18a53_idx'), models.Index(fields=['environment', 'status'], name='device_environ_f3d76b_idx'), models.Index(fields=['last_seen'], name='device_last_se_415629_idx')],
            },
        ),
    ]
