# Generated by Django 6.0.3 on 2026-04-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='os_version',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
