# Generated by Django 6.0.3 on 2026-04-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_device_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='compliance_rate',
            field=models.FloatField(db_index=True, default=100.0),
        ),
    ]
