# Generated by Django 6.0.3 on 2026-04-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_device_compliance_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='inventory_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
