# Generated by Django 6.0.3 on 2026-04-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_device_key_rotation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_scan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
