# Generated by Django 6.0.3 on 2026-04-11 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_device_last_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='lane_config',
            field=models.JSONField(blank=True, default=dict, help_text='Lane scheduler config: {fast_lane: {interval, concurrency, ...}, slow_lane: {...}}'),
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('heartbeat', 'Heartbeat'), ('scan_start', 'Scan Started'), ('scan_complete', 'Scan Complete'), ('patch_install_start', 'Patch Install Started'), ('patch_install_success', 'Patch Installed'), ('patch_install_failed', 'Patch Install Failed'), ('deployment_start', 'Deployment Started'), ('deployment_complete', 'Deployment Complete'), ('deployment_failed', 'Deployment Failed'), ('reboot_requested', 'Reboot Requested'), ('reboot_complete', 'Reboot Complete'), ('config_change', 'Config Changed'), ('key_rotated', 'API Key Rotated'), ('agent_online', 'Agent Online'), ('agent_offline', 'Agent Offline'), ('slow_lane_complete', 'Inventory Collected'), ('error', 'Error')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='agent', max_length=100)),
                ('deployment_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('patch_id', models.UUIDField(blank=True, null=True)),
                ('execution_lane', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.device')),
            ],
            options={
                'db_table': 'device_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', '-created_at'], name='device_even_device__024bb7_idx'), models.Index(fields=['device', 'event_type'], name='device_even_device__ab89b0_idx')],
            },
        ),
    ]
