# Generated by Django 6.0.3 on 2026-04-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samlconfiguration',
            name='attribute_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='JSON mapping of SAML attribute names to User field names. Example: {"email": "email", "cn": "full_name", "memberOf": "role"}'),
        ),
        migrations.AlterField(
            model_name='samlconfiguration',
            name='auto_create_users',
            field=models.BooleanField(default=True, help_text='Automatically provision a new User account on first SAML login.'),
        ),
        migrations.AlterField(
            model_name='samlconfiguration',
            name='auto_update_attrs',
            field=models.BooleanField(default=True, help_text='Overwrite full_name / department from SAML attrs on every login.'),
        ),
        migrations.AlterField(
            model_name='samlconfiguration',
            name='default_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='viewer', help_text='Role assigned when the SAML response does not include a role attribute.', max_length=20),
        ),
        migrations.AlterField(
            model_name='samlconfiguration',
            name='sp_entity_id',
            field=models.CharField(blank=True, help_text='SP EntityID. Defaults to <base_url>/api/v1/saml/<id>/metadata/ if blank.', max_length=500),
        ),
    ]
