# Generated by Django 6.0.3 on 2026-04-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_source_fullname'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_source_e7929e_idx',
            old_name='accounts_user_source_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('viewer', 'Viewer'), ('agent', 'Agent')], db_index=True, default='viewer', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='source',
            field=models.CharField(choices=[('local', 'Local'), ('ldap', 'LDAP'), ('saml', 'SAML')], db_index=True, default='local', max_length=10),
        ),
    ]
