# Generated by Django 6.0.3 on 2026-04-04 18:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('patches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('rolling_back', 'Rolling Back')], default='draft', max_length=20)),
                ('strategy', models.CharField(choices=[('immediate', 'Immediate'), ('canary', 'Canary'), ('rolling', 'Rolling'), ('maintenance', 'Maintenance Window')], default='rolling', max_length=20)),
                ('canary_percentage', models.IntegerField(default=5)),
                ('wave_size', models.IntegerField(default=50)),
                ('wave_delay_minutes', models.IntegerField(default=15)),
                ('max_failure_percentage', models.FloatField(default=5.0)),
                ('requires_reboot', models.BooleanField(default=False)),
                ('maintenance_window_start', models.TimeField(blank=True, null=True)),
                ('maintenance_window_end', models.TimeField(blank=True, null=True)),
                ('total_devices', models.IntegerField(default=0)),
                ('completed_devices', models.IntegerField(default=0)),
                ('failed_devices', models.IntegerField(default=0)),
                ('current_wave', models.IntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deployments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deployments', to=settings.AUTH_USER_MODEL)),
                ('patches', models.ManyToManyField(related_name='deployments', to='patches.patch')),
                ('target_groups', models.ManyToManyField(related_name='deployments', to='inventory.devicegroup')),
            ],
            options={
                'db_table': 'deployment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wave_number', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('rolled_back', 'Rolled Back')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='deployments.deployment')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_targets', to='inventory.device')),
            ],
            options={
                'db_table': 'deployment_target',
            },
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['status', '-created_at'], name='deployment_status_3db641_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['scheduled_at'], name='deployment_schedul_056db6_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymenttarget',
            index=models.Index(fields=['deployment', 'wave_number', 'status'], name='deployment__deploym_cb4eae_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymenttarget',
            index=models.Index(fields=['device', '-started_at'], name='deployment__device__520610_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deploymenttarget',
            unique_together={('deployment', 'device')},
        ),
    ]
