# Generated by Django 6.0.3 on 2026-04-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_deploymentevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deploymentevent',
            new_name='deployment__deploym_79f42c_idx',
            old_name='dep_event_dep_type_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='deploymentevent',
            new_name='deployment__deploym_d65422_idx',
            old_name='dep_event_dep_device_ts_idx',
        ),
    ]
