# Generated by Django 6.0.3 on 2026-04-04 18:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='imported', max_length=20)),
                ('vendor', models.CharField(max_length=100)),
                ('kb_article', models.URLField(blank=True)),
                ('cve_ids', models.JSONField(blank=True, default=list)),
                ('applicable_os', models.JSONField(default=list)),
                ('package_name', models.CharField(blank=True, max_length=200)),
                ('package_version', models.CharField(blank=True, max_length=100)),
                ('file_url', models.URLField(blank=True)),
                ('file_hash_sha256', models.CharField(blank=True, max_length=64)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('requires_reboot', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='patches.patch')),
            ],
            options={
                'db_table': 'patch',
                'ordering': ['-released_at'],
            },
        ),
        migrations.CreateModel(
            name='DevicePatchStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('missing', 'Missing'), ('pending', 'Pending'), ('downloading', 'Downloading'), ('installing', 'Installing'), ('installed', 'Installed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='missing', max_length=20)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_statuses', to='inventory.device')),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_statuses', to='patches.patch')),
            ],
            options={
                'db_table': 'device_patch_status',
            },
        ),
        migrations.AddIndex(
            model_name='patch',
            index=models.Index(fields=['severity', 'status'], name='patch_severit_f71943_idx'),
        ),
        migrations.AddIndex(
            model_name='patch',
            index=models.Index(fields=['vendor', 'status'], name='patch_vendor_6c5c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='patch',
            index=models.Index(fields=['-released_at'], name='patch_release_d14406_idx'),
        ),
        migrations.AddIndex(
            model_name='devicepatchstatus',
            index=models.Index(fields=['device', 'state'], name='device_patc_device__1b2e65_idx'),
        ),
        migrations.AddIndex(
            model_name='devicepatchstatus',
            index=models.Index(fields=['patch', 'state'], name='device_patc_patch_i_92a85a_idx'),
        ),
        migrations.AddIndex(
            model_name='devicepatchstatus',
            index=models.Index(fields=['state', '-last_attempt'], name='device_patc_state_530f2a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicepatchstatus',
            unique_together={('device', 'patch')},
        ),
    ]
