# Generated by Django 6.0.3 on 2026-04-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0002_patch_jsonfields_varchar_to_jsonb'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='status_notes',
            field=models.TextField(blank=True),
        ),
    ]
