# Generated by Django 6.0.3 on 2026-04-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0003_patch_status_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='cvss_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
