# Generated by Django 6.0.3 on 2026-04-09 05:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0004_patch_cvss_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('overall_compliance', models.FloatField()),
                ('total_devices', models.IntegerField()),
                ('compliant_devices', models.IntegerField()),
                ('critical_missing', models.IntegerField()),
            ],
            options={
                'db_table': 'compliance_snapshot',
                'ordering': ['-timestamp'],
            },
        ),
    ]
