# Generated by Django 6.0.3 on 2026-04-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0006_compliance_materialized_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicepatchstatus',
            name='execution_duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicepatchstatus',
            name='execution_lane',
            field=models.CharField(blank=True, choices=[('fast', 'Fast Lane'), ('slow', 'Slow Lane'), ('', 'Not Set')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='devicepatchstatus',
            name='state',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('missing', 'Missing'), ('pending', 'Pending'), ('downloading', 'Downloading'), ('installing', 'Installing'), ('installed', 'Installed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('pending_reboot', 'Pending Reboot')], default='missing', max_length=20),
        ),
    ]
